#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

: "${CODEXNEXT_RELAY_URL:?CODEXNEXT_RELAY_URL is required}"
: "${CODEXNEXT_OWNER_TOKEN:?CODEXNEXT_OWNER_TOKEN is required}"
: "${CODEXNEXT_PUBLIC_ORIGIN:?CODEXNEXT_PUBLIC_ORIGIN is required}"
: "${CODEXNEXT_WEB_AUTH_PASSWORD_HASH:?CODEXNEXT_WEB_AUTH_PASSWORD_HASH is required}"
: "${CODEXNEXT_WEB_SESSION_SECRET:?CODEXNEXT_WEB_SESSION_SECRET is required}"

export NEXT_PUBLIC_CODEXNEXT_RELAY_URL="$CODEXNEXT_RELAY_URL"
export CODEXNEXT_RELAY_URL
export CODEXNEXT_OWNER_TOKEN
export CODEXNEXT_PUBLIC_ORIGIN
export CODEXNEXT_WEB_AUTH_PASSWORD_HASH
export CODEXNEXT_WEB_SESSION_SECRET

if [[ -n "${CODEXNEXT_DISABLE_RELAY_FULL_ACCESS:-}" ]]; then
  export NEXT_PUBLIC_CODEXNEXT_DISABLE_RELAY_FULL_ACCESS="$CODEXNEXT_DISABLE_RELAY_FULL_ACCESS"
  export CODEXNEXT_DISABLE_RELAY_FULL_ACCESS
fi

if [[ -n "${CODEXNEXT_ALLOW_URL_TOKEN:-}" ]]; then
  export NEXT_PUBLIC_CODEXNEXT_ALLOW_URL_TOKEN="$CODEXNEXT_ALLOW_URL_TOKEN"
fi

HOST="${CODEXNEXT_WEB_HOST:-0.0.0.0}"
PORT="${CODEXNEXT_WEB_PORT:-3002}"

cd "$ROOT_DIR"
exec pnpm --filter @codexnext/web exec next start -H "$HOST" -p "$PORT"
